# =================
# Release Changelog
# =================

# .github/release.yml
# see https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions[bot]

  categories:
    # BREAKING CHANGES
    # ----------------

    - title: 🚧 Breaking Changes
      labels:
        - major
        - breaking-change

    # FEATURES
    # --------

    - title: 🚀 Features
      labels:
        - minor
        - enhancement
        - feature

    # FIXES
    # -----

    - title: 🛠 Fixes
      labels:
        - patch
        - bug
        - fix

    # MISCELLANEOUS
    # -------------

    - title: 📃 Miscellaneous
      labels:
        - "*"
